# Transformer Model Training

This notebook loads the processed transformer inputs created in "pre-process.ipynb" and prepares them for model training.

In [1]:
import numpy as np
import pandas as pd

## Load saved transformer arrays

In [2]:
X_train_input_ids = np.load("X_train_input_ids.npy")
X_train_attention_mask = np.load("X_train_attention_mask.npy")

X_val_input_ids = np.load("X_val_input_ids.npy")
X_val_attention_mask = np.load("X_val_attention_mask.npy")

X_test_input_ids = np.load("X_test_input_ids.npy")
X_test_attention_mask = np.load("X_test_attention_mask.npy")

y_train = np.load("y_train.npy")
y_val = np.load("y_val.npy")
y_test = np.load("y_test.npy")

In [5]:
X_train_input_ids

array([[ 101, 4005, 1024, ..., 2017, 2066,  102],
       [ 101, 8013, 1024, ...,    0,    0,    0],
       [ 101, 4005, 1024, ..., 3100, 1010,  102],
       ...,
       [ 101, 8013, 1024, ..., 3362, 2041,  102],
       [ 101, 4005, 1024, ...,    0,    0,    0],
       [ 101, 8013, 1024, ..., 1012, 4005,  102]], shape=(774, 512))

In [6]:
X_train_attention_mask

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]], shape=(774, 512))

In [7]:
y_train

array([1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 0,

These arrays are loaded from the preprocessing notebook so that model training and preprocessing remain in separate notebooks.

In [8]:
print("X_train_input_ids shape:", X_train_input_ids.shape)
print("X_train_attention_mask shape:", X_train_attention_mask.shape)
print("X_val_input_ids shape:", X_val_input_ids.shape)
print("X_val_attention_mask shape:", X_val_attention_mask.shape)
print("X_test_input_ids shape:", X_test_input_ids.shape)
print("X_test_attention_mask shape:", X_test_attention_mask.shape)

print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

X_train_input_ids shape: (774, 512)
X_train_attention_mask shape: (774, 512)
X_val_input_ids shape: (194, 512)
X_val_attention_mask shape: (194, 512)
X_test_input_ids shape: (30, 512)
X_test_attention_mask shape: (30, 512)
y_train shape: (774,)
y_val shape: (194,)
y_test shape: (30,)


In [9]:
print("Train label counts:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nValidation label counts:")
print(pd.Series(y_val).value_counts().sort_index())

print("\nTest label counts:")
print(pd.Series(y_test).value_counts().sort_index())

Train label counts:
0    327
1    433
2     14
Name: count, dtype: int64

Validation label counts:
0     82
1    109
2      3
Name: count, dtype: int64

Test label counts:
0    10
1    10
2    10
Name: count, dtype: int64


## DistilBERT classifier

Use a pretrained DistilBERT model for 3-class sentiment classification and fine-tune it.

In [12]:
import torch
import wandb
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertForSequenceClassification, get_linear_schedule_with_warmup
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

In [15]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("Using device:", device) ## Because my device is Apple M1 with 16 GB memory


Using device: mps


We use the same DistilBERT checkpoint as in preprocessing so the tokenization and model vocabulary remain aligned.

In [16]:
model_checkpoint = "distilbert-base-uncased"
num_labels = 3

model = DistilBertForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels
)
model.to(device)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 5695.46it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)


* the pretrained DistilBERT base model loaded correctly.
* the classification head for your 3 classes was newly created

### Datasets and dataloaders (For PyTorch)

In [17]:
class SentimentDataset(Dataset):
    def __init__(self, input_ids, attention_mask, labels):
        self.input_ids = torch.tensor(input_ids, dtype=torch.long)
        self.attention_mask = torch.tensor(attention_mask, dtype=torch.long)
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.labels[idx]
        }

In [18]:
train_dataset = SentimentDataset(X_train_input_ids, X_train_attention_mask, y_train)
val_dataset = SentimentDataset(X_val_input_ids, X_val_attention_mask, y_val)
test_dataset = SentimentDataset(X_test_input_ids, X_test_attention_mask, y_test)

batch_size = 8

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

Train batches: 97
Validation batches: 25
Test batches: 4


A small batch size is used because transformer models require substantial memory.

### Optimizer and scheduler

In [19]:
epochs = 3
learning_rate = 2e-5

optimizer = AdamW(model.parameters(), lr=learning_rate)
total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

A low learning rate is chosen because we are fine-tuning a pretrained model rather than training a new model from scratch.

### Handle class imbalance with weighted loss

In [20]:
class_counts = np.bincount(y_train)
class_weights = len(y_train) / (len(class_counts) * class_counts)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)

print("Class counts:", class_counts)
print("Class weights:", class_weights)

Class counts: [327 433  14]
Class weights: tensor([ 0.7890,  0.5958, 18.4286], device='mps:0')


Weighted loss is used because the classes are imbalanced, especially the positive class.

### Training and evaluation functions